apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data
  labels:
    app: {{ include "wordpress.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
