name: Deploy Wordpress

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save kubeconfig to file
        run: |
          echo ${{ secrets.KUBECONFIG }} | base64 -d > /tmp/config

      - name: Build dependencies
        run: |
          helm dependency build wordpress
        env:
          KUBECONFIG: /tmp/config  

      - name: Deploy Wordpress
        run: |
          helm install wordpress ./wordpress
        env:
          KUBECONFIG: /tmp/config

      - name: Remove kubeconfig info
        run: rm -f /tmp/config
